version: '3.8'

services:

  gateway-service:
    container_name: gateway-service
    build:
      context: ./gateway-service/.
    ports:
      - "8088:8088"
    environment:
      - "SERVICE_PORT=8088"
      - "IDENTITY_SERVICE_ADDRESS=identity-service"
      - "IDENTITY_SERVICE_PORT=8091"
      - "BOOKING_SERVICE_ADDRESS=booking-service"
      - "BOOKING_SERVICE_PORT=8090"
    depends_on:
      - identity-service
      - booking-service

  db_identity:
    container_name: db_identity
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./init-identity-db.sql:/docker-entrypoint-initdb.d/init-identity-db.sql
#      - db-identity-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: db_identity_example

  identity-service:
    container_name: identity-service
    build:
      context: ./identity-service/.
    ports:
      - "8091:8091"
    environment:
      - "SERVICE_PORT=8091"
      - "POSTGRES_DB_SERVER_ADDRESS=db_identity"
      - "POSTGRES_DB_SERVER_PORT=5432"
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=db_identity_example"
    depends_on:
      - db_identity

  db_booking:
    container_name: db_booking
    image: postgres
    restart: always
    ports:
      - "5433:5433"
    volumes:
      - ./init-booking-db.sql:/docker-entrypoint-initdb.d/init-booking-db.sql
#      - db-booking-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: db_booking_example
      PGPORT: 5433

  booking-service:
    container_name: booking-service
    build:
      context: ./booking-service/.
    ports:
      - "8090:8090"
    environment:
      - "SERVICE_PORT=8090"
      - "POSTGRES_DB_SERVER_ADDRESS=db_booking"
      - "POSTGRES_DB_SERVER_PORT=5433"
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=db_booking_example"
      - "IDENTITY_SERVICE_ADDRESS=identity-service"
      - "IDENTITY_SERVICE_PORT=8091"

    depends_on:
      - db_booking

volumes:
  db-identity-data:
    external: false
  db-booking-data:
    external: false