version: '3.8'

services:
  db_identity:
    container_name: db_identity
    image: postgres
    volumes:
      - db-identity-data:/var/lib/postgresql/data
      - ./init-identity-db.sql:/docker-entrypoint-initdb.d/init-identity-db.sql
    environment:
      POSTGRES_PASSWORD: ${IDENTITY_POSTGRES_PASSWORD}

  db_booking:
    container_name: db_booking
    image: postgres
    volumes:
      - db-booking-data:/var/lib/postgresql/data
      - ./init-booking-db.sql:/docker-entrypoint-initdb.d/init-booking-db.sql
    environment:
      POSTGRES_PASSWORD: ${BOOKING_POSTGRES_PASSWORD}
      PGPORT: ${BOOKING_POSTGRES_DB_SERVER_PORT}

  identity-service:
    container_name: identity-service
    build:
      context: ./identity-service/.
      args:
        - IDENTITY_DEBUG_PORT=${IDENTITY_DEBUG_PORT}
    ports:
      - ${IDENTITY_DEBUG_PORT}:${IDENTITY_DEBUG_PORT} # for debugging
    environment:
      - SERVICE_PORT=${IDENTITY_SERVICE_PORT}
      - POSTGRES_DB_SERVER_ADDRESS=${IDENTITY_POSTGRES_DB_SERVER_ADDRESS}
      - POSTGRES_DB_SERVER_PORT=${IDENTITY_POSTGRES_DB_SERVER_PORT}
      - POSTGRES_USER=${IDENTITY_POSTGRES_USER}
      - POSTGRES_PASSWORD=${IDENTITY_POSTGRES_PASSWORD}
    depends_on:
      - db_identity

  booking-service:
    container_name: booking-service
    build:
      context: ./booking-service/.
      args:
        - BOOKING_DEBUG_PORT=${BOOKING_DEBUG_PORT}
    ports:
      - ${BOOKING_DEBUG_PORT}:${BOOKING_DEBUG_PORT} # for debugging
    environment:
      - SERVICE_PORT=${BOOKING_SERVICE_PORT}
      - POSTGRES_DB_SERVER_ADDRESS=${BOOKING_POSTGRES_DB_SERVER_ADDRESS}
      - POSTGRES_DB_SERVER_PORT=${BOOKING_POSTGRES_DB_SERVER_PORT}
      - POSTGRES_USER=${BOOKING_POSTGRES_USER}
      - POSTGRES_PASSWORD=${BOOKING_POSTGRES_PASSWORD}
      - IDENTITY_SERVICE_ADDRESS=${IDENTITY_SERVICE_ADDRESS}
      - IDENTITY_SERVICE_PORT=${IDENTITY_SERVICE_PORT}
    depends_on:
      - db_booking
      - identity-service

  gateway-service:
    container_name: gateway-service
    build:
      context: ./gateway-service/.
      args:
        - GATEWAY_DEBUG_PORT=${GATEWAY_DEBUG_PORT}
    ports:
      - ${GATEWAY_SERVICE_PORT}:${GATEWAY_SERVICE_PORT}
      - ${GATEWAY_DEBUG_PORT}:${GATEWAY_DEBUG_PORT} # for debugging
    environment:
      - SERVICE_PORT=${GATEWAY_SERVICE_PORT}
      - IDENTITY_SERVICE_ADDRESS=${IDENTITY_SERVICE_ADDRESS}
      - IDENTITY_SERVICE_PORT=${IDENTITY_SERVICE_PORT}
      - BOOKING_SERVICE_ADDRESS=${BOOKING_SERVICE_ADDRESS}
      - BOOKING_SERVICE_PORT=${BOOKING_SERVICE_PORT}
    depends_on:
      - identity-service
      - booking-service

volumes:
  db-identity-data:
  db-booking-data: